version: "2.4"
services:
  tropico:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - ./source:/app/:ro
  test:
    build:
      context: .
      dockerfile: ./test.Dockerfile
    volumes:
    - ./source:/app/:ro
